language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

cache:
    directories:
      - $HOME/.gradle/caches

after_script:
  - ./gradlew jacocoTestReport
  - bash <(curl -s https://codecov.io/bash)