language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

script: ./gradlew assemble check --stacktrace
  
#cache:
#    directories:
#      - $HOME/.gradle/caches

after_script:
  - ./gradlew jacocoTestReport
  - bash <(curl -s https://codecov.io/bash)